up

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,32 +1,50 @@
-# This is a basic workflow to help you get started with Actions
+name: main
 
-name: CI
-
-# Controls when the workflow will run
 on:
-  
-
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
+  
+permissions:
+  contents: read
+  issues: write
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+  main:
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v4
-
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Setup Terraform CLI
+        uses: hashicorp/setup-terraform@v3
+      - name: Setup Ansible
+        run: sudo apt-get install -y ansible
+      - name: Check VARS secret exists
+        env:
+          VARS_JSON: ${{ secrets.VARS_JSON }}
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          if [ -z "$VARS_JSON" ]; then
+            echo "Error: Secret VARS is missing or empty"
+            exit 1
+          fi
+      - name: Export VARS env as outputs
+        id: export_vars
+        env:
+          VARS_JSON: ${{ secrets.VARS_JSON }}
+        run: |
+          echo "$VARS_JSON" | jq -r 'to_entries[] | "\(.key)=\(.value)"' \
+            | while IFS= read -r line; do
+                echo "$line" >> $GITHUB_OUTPUT
+                echo "Output ${line%%=*}"
+              done
+      - name: Create vars.json from secret
+        run: |
+          echo '${{ secrets.VARS_JSON }}' > vars.json
+      - name: Authenticate to GCP
+        uses: google-github-actions/auth@v2
+        with:
+          credentials_json: ${{ secrets.SERVICE_ACCOUNT }} 
+      - name: Setup gcloud
+        uses: google-github-actions/setup-gcloud@v2
+        with:
+          project_id: ${{steps.export_vars.outputs.gcloud_project_id}}
+      - name: Test GCP access
+        run: gcloud projects describe ${{ secrets.GCP_PROJECT_ID }}
